#!/usr/bin/python3

import sys
import json

f1, f2 = sys.argv[1:3]

notificationString = open( f1 ).read()
notification = json.loads( notificationString )
message = notification
if "message" in notification:
    message = notification["message"]

# Who has sent the message?
sender = ""
if 'sender_display_name' in message:
    sender = message["sender_display_name"]
elif 'sender' in message:
    sender = message["sender"]

# What is the body of the message?
body = "New encrypted Message"
if 'content' in message and 'body' in message["content"]:
    body = message["content"]["body"]
if 'room_name' in message and message["room_name"] != sender:
    body = sender + ": " + message["content"]["body"]

# What is the room name?
room_name = "Unknown"
if 'room_name' in message:
    room_name = message["room_name"]
elif 'sender_display_name' in message:
    room_name = message["sender_display_name"]
elif 'sender' in message:
    room_name = message["sender"]

# What is the type of the message?
type = "null"
showBubble = False
if 'type' in message and message["type"] == "m.room.message":
    type = "message"
    showBubble = True

if type == "m.room.member" and 'content' in message and 'membership' in message["content"] and message["content"]["membership"] == "invite" and 'user_is_target' in message and message["user_is_target"] == true:
    type = "invite"
    showBubble = True

# What is the tag?
tag = "NO_MESSAGE_ID"
if 'room_id' in message:
    tag = message["room_id"]

# How many unread notifications are there?
unread = 0
unread_visible = False
if 'counts' in message and 'unread' in message["counts"]:
    unread = message["counts"]["unread"]
    if unread > 0:
        unread_visible = True

# Vibration should be longer if the prio is high
vibduration = 200
if 'prio' in message and message['prio'] == "high":
    vibduration = 1000

action = ["fluffychat://" + tag]

notification["notification"] = {}
notification["notification"]["sound"] = showBubble
notification["notification"]["tag"] = tag
notification["notification"]["emblem-counter"] = {}
notification["notification"]["emblem-counter"]["count"] = unread
notification["notification"]["emblem-counter"]["visible"] = unread_visible
if showBubble:
    notification["notification"]["vibrate"] = {}
    notification["notification"]["vibrate"]["duration"] = vibduration
    notification["notification"]["vibrate"]["pattern"] = [vibduration, vibduration]
    notification["notification"]["vibrate"]["repeat"] = 2
    notification["notification"]["card"] = {}
    notification["notification"]["card"]["actions"] = action
    notification["notification"]["card"]["summary"] = room_name
    notification["notification"]["card"]["body"] = body
    notification["notification"]["card"]["persist"] = True
    notification["notification"]["card"]["popup"] = True
    notification["notification"]["card"]["icon"] = "contact"

open( f2, "w" ).write( json.dumps(notification) )
